CREATE TABLE organizations (
    id VARCHAR(255) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    owner VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    cep VARCHAR(20) NOT NULL,
    city VARCHAR(255) NOT NULL,
    whatsapp VARCHAR(20) NOT NULL,
    password VARCHAR(255) NOT NULL
);
